# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    # continuous integration
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish -o ./app
    # continuous deployment
    - name: Copy application via scp to the server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.MAINSITE_IP }}
        username: ${{ secrets.MAINSITE_USER }}
        passphrase: ${{ secrets.MAINSITE_PASSPHRASE }}
        key: ${{ secrets.MAINSITE_PRIVATEKEY }}
        source: "./app"
        target: "~/dotnet/SistemasWeb01/."
        
    - name: Restart deployed service to get latest changes
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo systemctl restart websystems01.service
        host: ${{ secrets.MAINSITE_IP }}
        username: ${{ secrets.MAINSITE_USER }}
        passphrase: ${{ secrets.MAINSITE_PASSPHRASE }}
        privateKey: ${{ secrets.MAINSITE_PRIVATEKEY}}
